/* Marketing copy, transcribed from data/site.js in the CASPAA repo. */
window.SITE = {
  CONTACT: {
    email: 'info@caspaa.org',
    phones: ['0803 201 1561', '0803 200 1561'],
    tagline: 'The all-in-one digital infrastructure for African schools.',
  },
  NAV_LINKS: [
    { label: 'Home', href: '#' },
    { label: 'Solutions', href: '#roles' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Contact', href: '#contact' },
  ],
  HERO: {
    eyebrow: 'THE SCHOOL OPERATING SYSTEM',
    title: 'Run your entire school on one platform.',
    titles: [
      'Run your entire school on one platform.',
      'Collect every fee without chasing a parent.',
      "See your school's numbers in real time.",
      "Keep running when the network doesn't.",
    ],
    subtitle: 'One Edu-Fintech operating system for admissions, fees, attendance, results and accounting. Online or offline, you keep complete visibility and control.',
    microtrust: 'No spreadsheets. No manual reconciliation. No waiting for reports.',
  },
  METRICS: [
    { value: '₦3.6m+', label: 'Fees collected & reconciled' },
    { value: '2,000+', label: 'Students managed' },
    { value: '50+', label: 'Schools running on CASPAA' },
    { value: '99.9%', label: 'Uptime, online & offline' },
  ],
  PROBLEMS: [
    { icon: 'trending-down', title: 'Revenue leakage', body: 'Untracked fees, missed reminders and manual reconciliation quietly drain income every term.' },
    { icon: 'puzzle', title: 'Disconnected tools', body: 'Records, fees, accounting and communication live in separate systems that never sync.' },
    { icon: 'wifi-off', title: 'Internet dependency', body: 'When the network drops, work stops — attendance, payments and updates all stall.' },
    { icon: 'hourglass', title: 'Reports that arrive too late', body: 'By the time you get the numbers, the decision window has already closed.' },
  ],
  PLATFORM_TILES: [
    { icon: 'cloud-off', title: 'Works Offline', body: 'Mark attendance and keep working with no signal; syncs automatically when you reconnect.' },
    { icon: 'card', title: 'Payments', body: 'Parents pay fees in 30 seconds through secure, integrated payment infrastructure.' },
    { icon: 'bank', title: 'Fee Financing', body: 'School-fee lending with loans approved in as little as 24 hours.' },
    { icon: 'sparkles', title: 'AI Assistant', body: 'Write report comments, insights and summaries instantly.' },
    { icon: 'file-edit', title: 'CBT & Learning', body: 'Run digital tests and exams for every class.' },
    { icon: 'check-circle', title: 'Digital Consent', body: 'Approve activities and trips online — no paper forms.' },
  ],
  ROLES: [
    { slug: 'proprietors', tab: 'Proprietors', name: 'Proprietors & School Owners', headline: 'Total visibility. Total control. From anywhere.', body: 'Open your dashboard and instantly see the health of your school — revenue collected today, outstanding fees, enrolment trends, staff attendance and financial performance. Spot revenue leakage before it happens, and make decisions backed by real numbers, not guesswork.', punch: 'Most systems tell you what happened. CASPAA helps you decide what happens next.' },
    { slug: 'principals', tab: 'Principals', name: 'Principals & Administrators', headline: 'Run the whole school day from a single screen.', body: 'From admissions to academics to operations, CASPAA gives administrators one command centre. Manage enrolment, oversee staff, track attendance, publish results and keep parents informed — all without switching tools.', punch: 'One command centre for the entire school.' },
    { slug: 'teachers', tab: 'Teachers', name: 'Teachers', headline: 'Less admin. More teaching.', body: "Clock in, take attendance, set assignments, grade results and message parents — in minutes. CASPAA's AI-powered tools even help you write report comments and plan lessons, so you get your evenings back.", punch: 'Get your evenings back.' },
    { slug: 'parents', tab: 'Parents', name: 'Parents', headline: "Your child's school, in your pocket.", body: 'Pay fees in seconds, approve trips digitally, follow attendance and results in real time, and stay in the loop on everything — from house points to health and welfare. No more missed notices, no more paper forms.', punch: 'Never miss a notice again.' },
    { slug: 'students', tab: 'Students', name: 'Students', headline: 'Everything you need to learn and stay on track.', body: 'Assignments, timetables, results and study resources in one place — plus house points and gamification that make progress feel rewarding.', punch: 'Progress that feels rewarding.' },
    { slug: 'finance', tab: 'Finance', name: 'Finance & Accounting', headline: 'From collection to reconciliation, automatically.', body: 'CASPAA turns fee collection into a closed loop: parents pay through secure channels, payments reconcile in real time, and your books stay current. Generate P&L, trial balance and balance sheet reports without a separate accounting system.', punch: 'A closed loop, from payment to books.' },
  ],
  COMPARISON: [
    ['Manages records', 'Powers school operations'],
    ['Tracks fees', 'Automates collections & reconciliation'],
    ['Generates reports', 'Delivers business intelligence'],
    ['Manual consent forms', 'Digital parent consent management'],
    ['Internet dependent', 'Offline-first capability'],
    ['Basic admissions', 'End-to-end admissions & enrolment'],
    ['Separate accounting systems', 'Integrated accounting & finance'],
    ['Basic communication', 'WhatsApp, email & automated notifications'],
  ],
  ADVANTAGES: [
    'Offline technology capabilities', 'Digital staff attendance management', 'Digital parent consent',
    'Digital clock-in / clock-out student attendance', 'Live chat & 24/7 client support',
    'Secure payment infrastructure', 'Admission & new-intake management', 'Automated event & fee reminders',
    'Executive dashboards & analytics', 'WhatsApp & email engagement', 'Accounting management',
    'Revenue management', 'Real-time automated reconciliation', 'Customisation',
  ],
  OUTCOMES: [
    { icon: 'trending-up', title: 'Increase fee-collection efficiency', body: 'Automated reminders and instant payments get more fees in, faster.' },
    { icon: 'lock', title: 'Eliminate revenue leakages', body: 'Real-time reconciliation closes the gaps manual tracking misses.' },
    { icon: 'message', title: 'Improve parent engagement', body: 'Reach every family on WhatsApp and email, automatically.' },
    { icon: 'calculator', title: 'Strengthen financial control', body: 'Integrated accounting keeps your books accurate and current.' },
    { icon: 'globe', title: 'Operate online & offline', body: 'Never let connectivity stop your school day.' },
    { icon: 'headset', title: 'Dedicated real-time support', body: 'Live chat and 24/7 help whenever you need it.' },
    { icon: 'folders', title: 'Simplify administration', body: 'One system replaces the many tools you juggle today.' },
    { icon: 'users', title: 'Enhance staff accountability', body: 'Digital attendance and clear ownership across teams.' },
    { icon: 'lightbulb', title: 'Gain business intelligence', body: 'Turn everyday data into decisions that grow your school.' },
  ],
  STEPS: [
    { n: 1, title: 'Book a demo', body: "See CASPAA on your school's real workflows." },
    { n: 2, title: 'Onboard & import', body: 'We migrate your students, staff and data for you.' },
    { n: 3, title: 'Train your team', body: '2–3 days of hands-on training included with setup.' },
    { n: 4, title: 'Go live', body: 'Start collecting fees, marking attendance and running reports — with 24/7 support behind you.' },
  ],
  SECURITY: [
    { icon: 'lock', label: 'Encrypted data, in transit & at rest' },
    { icon: 'shield', label: 'Secure payment infrastructure' },
    { icon: 'user', label: 'Role-based access controls' },
    { icon: 'sync', label: 'Automated backups & sync' },
    { icon: 'clock', label: '99.9% uptime' },
  ],
  PRICING: [
    { name: 'Standard', price: '₦3,000', unit: 'per student / term', tagline: 'Everything a school needs to go digital.', popular: false, setup: '₦100,000 setup · 2 days training',
      features: ['Curriculum & timetable management', 'Online payments & fee management', 'Student information system', 'Parent portal & teacher portal', 'Attendance management', 'Results & report cards', 'Digital consent form', 'Executive dashboards & analytics', 'Offline-first technology', 'CBT & online assessments'] },
    { name: 'Premium', price: '₦5,000', unit: 'per student / term', tagline: 'Everything in Standard, plus fintech, HR and advanced operations.', popular: true, setup: '₦150,000 setup · 3 days training', inherits: 'Everything in Standard, plus:',
      features: ['Accounting reports', 'AI academic insights', 'AI report comments', 'Payroll management', 'School-fee lending', 'Staff HR management', 'Transport management', 'End-to-end admissions & enrolment', 'Accounting package (P&L, trial balance, balance sheet)', 'Revenue analytics'] },
    { name: 'Ultimate', price: '₦5,000+', unit: 'per student / term', tagline: 'For groups and multi-branch schools that need scale.', popular: false, gold: true, inherits: 'Everything in Premium, plus:',
      features: ['Advanced analytics dashboard', 'Multi-branch school support', 'Dedicated account manager'] },
  ],
  FAQ: [
    { q: 'Does CASPAA really work offline?', a: 'Yes. Core operations — attendance, tests, and day-to-day work — run fully offline and sync automatically when you reconnect.' },
    { q: 'How is CASPAA priced?', a: 'Per student, per term. Standard is ₦3,000, Premium is ₦5,000, and Ultimate is for multi-branch schools. A one-off setup fee (from ₦100,000) includes hands-on training. Prices are VAT exclusive.' },
    { q: 'Can parents pay fees through CASPAA?', a: 'Yes. Parents pay in about 30 seconds through secure channels, and every payment reconciles in real time. School-fee financing is also available.' },
    { q: 'Do I need a separate accounting system?', a: 'No. CASPAA includes integrated accounting — P&L, trial balance and balance sheet — on the Premium plan and above.' },
    { q: 'How long does setup take?', a: 'Most schools go live in days. We handle data migration and provide 2–3 days of training with setup.' },
    { q: 'Can CASPAA handle multiple branches?', a: 'Yes — the Ultimate plan includes multi-branch support, advanced analytics and a dedicated account manager.' },
    { q: 'What support do you offer?', a: 'Live chat and 24/7 client support, plus a dedicated account manager on Ultimate.' },
    { q: 'Can we customise CASPAA for our school?', a: 'Yes. Customisation is available; some post-acceptance adjustments may attract additional charges.' },
  ],
};
